version: '3'
services:
  client:
    image: venkats1/docker-react-client
    mem_limit: 128m
    hostname: client
  server:
    image: venkats1/docker-react-server
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PG_USER
      - PGHOST=$PG_HOST
      - PGDATABASE=$PG_DATABASE
      - PGPASSWORD=$PG_PASSWORD
      - PGPORT=$PG_PORT
  worker:
    image: venkats1/docker-react-worker
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: venkats1/docker-react-nginx
    hostname: nginx
    mem_limit: 128m
    ports:
      - "80:80"
